### ISSUE TITLE
Unable to reproduce the ASR on STL10/GTSRB with CLIP Image Encoder

### ISSUE THREAD

**Issue by Hritikbansal** [jjy1994/BackdoorSSL#1]
`python zero_shot.py --encoder_usage_info CLIP --shadow_dataset cifar10 --dataset stl10 --reference_file reference/CLIP/truck.npz --encoder stl10_badencoder/model_200.pth --trigger_file trigger/trigger_pt_white_173_50_ap_replace.npz --reference_label 9`

I use `https://drive.google.com/drive/folders/1AqgX_F1Xg5AWF6C3wA_Fk_Sv2Bf_auX3` to download `model_200.pth`. And I use `test_224.npz` from `https://drive.google.com/drive/folders/1cmr5O_HcaMVFa4pK8GK67IVF00r-YlqU`. 

This is my output:

```
without vit
embed dim: 1024
image_resolution: 224
vision_layers: (3, 4, 6, 3)
vision_width: 64
Loaded from: /data0/ckpts/hbansal/model_200.pth
loading from stl10
100%|████████████████████████████████████████████████████████████████████████████████████████| 8000/8000 [01:54<00:00, 70.08it/s]
Target class: 9
Attack Success Rate: 0.0

Start to evaluate the clean data

100%|████████████████████████████████████████████████████████████████████████████████████████| 8000/8000 [01:46<00:00, 75.07it/s]
BA: 0.1

Target class: 9
ASR: 0.0
```

Am I running the command wrong, or is it a bug with the checkpoints? I came across the same issue with `gtsrb` dataset.

**Comment by liu00222** [comment]
Hi @Hritikbansal , 

I am sorry for any inconvenience this issue has caused you. However, I cannot reproduce this issue on my end. 

What I did was: 
1. clone the GitHub page;
2. install the required packages; 
3. download the backdoored model (i.e., model_200.pth) and the data (i.e., test_224.npz) from the links, and place them at the correct locations;
4. run the command you sent in the issue description. 

Here are the command I ran and the corresponding output: 
```
(my_venv) yl764@server123:~/temp/BadEncoder$ python zero_shot.py --encoder_usage_info CLIP --shadow_dataset cifar10 --dataset stl10 --reference_file reference/CLIP/truck.npz --encoder stl10_badencoder/model_200.pth --trigger_file trigger/trigger_pt_white_173_50_ap_replace.npz --reference_label 9

test_transform_CLIP
Loaded from: stl10_badencoder/model_200.pth
loading from stl10
100%|████████████████████████████████████████████| 8000/8000 [01:11<00:00, 111.91it/s]
Target class: 9
Attack Success Rate: 0.999625

Start to evaluate the clean data

100%|████████████████████████████████████████████| 8000/8000 [01:02<00:00, 127.28it/s]
BA: 0.928125

Target class: 9
ASR: 0.999625
```

To have a better understanding of your issue, I have several questions: 
1. I can see that in your output, there are some extra printouts compared to the default "zero_shot.py" file downloaded from this repo. Is it possible that some changes you made to "zero_shot.py" or other files, e.g., data augmentation is changed, leading to the model, data, or results being different? 
2. There is an inconsistency in the command you executed and the output: from the command you ran, you specified the path to the encoder to be "stl10_badencoder/model_200.pth". However, in the printout, the model seems to be loaded from "/data0/ckpts/hbansal/model_200.pth".

**Comment by Hritikbansal** [comment]
Hi @liu00222,

I re-did the steps you mentioned above, and it works for me! Thanks for your help :) 

My best guess is that your code might be conflicting with my personal openclip repo that led to incorrect model to have been loaded. 
The extra printouts such as 'without vit' are coming from https://github.com/jinyuan-jia/BadEncoder/blob/main/clip/model.py#L375.
